### PR TITLE
Added states for Estonia

### PR DESCRIPTION
**Pull request by priitperna**

### CODE REVIEW

**Comment by daftspunk** [comment]
`EE-37` looks like an ISO code, are there meaningful state codes that can be used instead?

**Comment by dragontree** [comment]
I took them from the ISO 3166-2:EE standard.
County abbreviations are not used in Estonia so there is no real purpose for them.

**Comment by daftspunk** [comment]
You sure? A quick google search found this: http://www.geopostcodes.com/Estonia

HA, HI, IV, JR, etc.

**Comment by LukeTowers** [comment]
@priitperna Let us know if you're willing to make the requested changes or provide further information and we'll revisit merging

**Comment by priitperna** [comment]
As I said before. The county codes are not used in Estonia and therefore there are no meaningful codes.
They are just not used.

Statistics Estonia (the government agency that deals with these kinds of classifications) lists the ISO codes without the "EE-" prefix but they are not used publicly, so I dont think there is a clear preference in using the prefix or not.

**Comment by LukeTowers** [comment]
So these codes are not used anywhere period?

**Comment by priitperna** [comment]
Yes

**Comment by LukeTowers** [comment]
Whats the difference between using your original codes and @daftspunk's requested codes then? The other codes more closely align with the codes for other countries so if it really doesn't matter which is used I think I'd prefer to see the ones that more closely match the rest of the codebase instead

**Comment by priitperna** [comment]
Because I didnt find any reference to the codes @daftspunk mentioned in the government agency-s page which deals with these kinds of things.

**Comment by LukeTowers** [comment]
So the codes used by that agency are the ones that you use?

**Comment by priitperna** [comment]
They can be found [here](http://metaweb.stat.ee/view_xml.htm?id=4090708&siteLanguage=en).
The codes are the same as the ISO standard, just in a bit different format. But as they are not used in real life, I dont think it matters.

**Comment by LukeTowers** [comment]
Alright, I'll merge it then. Thanks for sticking with us as we figure this out :)

**Pull request merged**
