### PR TITLE
include México states

### PR DESCRIPTION
**Pull request by oscarnevarezleal**
Hi, I just included missing Mexico states 👍

### CODE REVIEW

**Comment by LukeTowers** [comment]
@oscarnevarezleal thanks!

**Comment by oscarnevarezleal** [comment]
I don´t know why,but I don´t see this changes in my project event after the plugin has updated to latest version. Am I missing something?

**Comment by LukeTowers** [comment]
@oscarnevarezleal that's because the version.yaml file wasn't updated so the marketplace doesn't see a new version to release. Also, you would need to reset the plugin's data to include these changes if you have already installed it.

You can also include this plugin by requiring rainlab/location-plugin with composer which will get the latest source directly from github.

**Comment by oscarnevarezleal** [comment]
@LukeTowers 
Oh I see now, thanks

**Comment by oscarnevarezleal** [comment]
Should I send a PR containing an update on version.yaml ?

**Comment by LukeTowers** [comment]
@oscarnevarezleal sure if you want. If you do, then please include in the update note every change that's occurred since the last bump to the version.yaml file.

**Comment by oscarnevarezleal** [comment]
Hi @LukeTowers can you review my PR?

**Comment by LukeTowers** [comment]
@oscarnevarezleal done

**Pull request merged**
