### PR TITLE
Country restrictions

### PR DESCRIPTION
**Pull request by tschortsch**
This pull request adds new option `countryRestriction` to restrict location lookup to defined countries.
Example: `countryRestriction: 'us,ch'` (Restrict adress lookup to United States of America and Switzerland)

### CODE REVIEW

**Comment by LukeTowers** [comment]
@tschortsch do you still want this merged?

**Comment by tschortsch** [comment]
If possible, of course ;)

**Comment by LukeTowers** [comment]
@tschortsch just to verify, have you tested this both with and without the option present?

**Comment by tschortsch** [comment]
I'm using my fork in this productive website and it works with and without the new options: https://github.com/repair-cafe/website/blob/master/.gitmodules#L15

**Comment by LukeTowers** [comment]
Awesome, thanks for your work on this @tschortsch!

**Pull request merged**
